dist: precise
language: node_js
node_js:
  - 6
  - 8
cache:
  directories:
  - node_modules

before_script:
  - npm install coveralls
  - npm install

script:
  - npm run test:coverage

after_success:
  cat ./coverage/lcov.info | node node_modules/.bin/coveralls
