version: '2'
services:
  httpd:
    image: jimbasilio/html5-httpd
    container_name: health-nlp-react 
    volumes:
      - ./docs:/usr/local/apache2/htdocs/
    restart: "always"
    environment:
      - VIRTUAL_HOST=www.lifescope-project.com
      - LETSENCRYPT_EMAIL=jdonado@jdonado.com
      - LETSENCRYPT_HOST=www.lifescope-project.com
    networks:
      - jdonado-nw
#    ports:
#      - "127.0.0.1:9000:80"
    expose:
      - 8888

networks:
   jdonado-nw:
     external:
       name: jdonado-nw
